# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: go-hello-world

before:
  hooks:
    # You may remove this if you don't use go modules.
    - env
builds:
  -
    id: "go-hello-world"
    dir: cmd
    goos:
      - linux
    goarch:
      - amd64

dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ toLower .Env.GITHUB_REPOSITORY_OWNER}}/go-hello-world:latest"
      - "ghcr.io/{{ toLower .Env.GITHUB_REPOSITORY_OWNER}}/go-hello-world:{{.Version}}"
    dockerfile: Dockerfile
    use: buildx
    skip_push: false
    build_flag_templates:
      - "--platform=linux/amd64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "latest"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
